jobs:
  - name: w16test
    type: runSh
    runtime:
      nodePool: dynamic__x86_64__WindowsServer_2016__c4_large 
    steps:
      - TASK:
          runtime:
            options:
              imageName: "drydock/w16"
              imageTag: master
          script:         
            - python --version
            - node --version
            - git lfs version
            - javac -version
            - ruby --version
            - gcloud version
            - aws --version
            - az --version
            - jfrog --version
            - terraform -version
            - packer --version
            - jq --version
            - cniversion
            - docker --version
            
