jobs:
  - name: w16test
    type: runSh
    runtime:
      nodePool: dynamic__x86_64__WindowsServer_2016__c4_large 
    steps:
      - TASK:
          runtime:
            options:
              imageName: "drydock/w16"
              imageTag: master
          script:  
            - git --version
            - python --version
            - node --version
            - git lfs version
            - ruby --version
            - gcloud version
            - aws --version
            - az --version
            - jfrog --version
            - terraform -version
            - packer --version
            - jq --version
            - kubectl version --client
            - docker --version
            - java --version
            - choco list
            - choco --version
  - name: dotnettest
    type: runSh
    runtime:
      nodePool: dynamic__x86_64__WindowsServer_2016__c4_large
    steps:
      - IN: w16test
      - TASK: 
          runtime:
            options:
              imageName: "drydock/w16dotnetcore"
              imageTag: master
          script:        
            - dotnet --version  
          
           
